// <auto-generated />
using System;
using FuncEnCasa.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FuncEnCasa.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Area", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdArea")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreArea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("_Id");

                    b.HasIndex("nombreArea")
                        .IsUnique();

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Barrio", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdBarrio")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreBarrio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("_Id");

                    b.HasIndex("nombreBarrio")
                        .IsUnique();

                    b.ToTable("Barrios");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Barrio_ZonaLocalidad", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdBarrioZL")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ZonaLId")
                        .HasColumnType("int");

                    b.Property<int?>("barrioId")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("ZonaLId");

                    b.HasIndex("barrioId");

                    b.ToTable("Barri_ZonaLocalidades");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Ciudad", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCiudad")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreCiudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("_Id");

                    b.HasIndex("nombreCiudad")
                        .IsUnique();

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Ciudad_BarrioZonaLocalidad", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCiudadBZL")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BarrioZLId")
                        .HasColumnType("int");

                    b.Property<int?>("ciudadId")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("BarrioZLId");

                    b.HasIndex("ciudadId");

                    b.ToTable("Ciudad_BarrioZonaLocalidades");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Ciudad_Departamento", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCiudadDepartamento")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ciudadId")
                        .HasColumnType("int");

                    b.Property<int?>("departamentoId")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("ciudadId");

                    b.HasIndex("departamentoId");

                    b.ToTable("Ciudad_Departamentos");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Correo", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCorreo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("_Id");

                    b.HasIndex("correo")
                        .IsUnique();

                    b.ToTable("Correos");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Correo_Usuario", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCorreoU")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CorreoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("idTipoContacto")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("CorreoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CorreoUsuarios");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Departamento", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDepartamento")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreDepart")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("_Id");

                    b.HasIndex("nombreDepart")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Direccion", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDireccion")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("tipoViviendaBId")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("direccion")
                        .IsUnique();

                    b.HasIndex("tipoViviendaBId");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Funcionario", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdFuncionario")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ciudadId")
                        .HasColumnType("int");

                    b.Property<int?>("correoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("direccionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("genero")
                        .HasColumnType("int");

                    b.Property<int>("idTipoContactoCorreo")
                        .HasColumnType("int");

                    b.Property<int>("idTipoContactoTelefono")
                        .HasColumnType("int");

                    b.Property<int>("idTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("sucursalId")
                        .HasColumnType("int");

                    b.Property<int?>("telefonoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("tipoSanguineo")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("ciudadId");

                    b.HasIndex("correoId");

                    b.HasIndex("direccionId");

                    b.HasIndex("sucursalId");

                    b.HasIndex("telefonoId");

                    b.HasIndex("usuarioId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Jerarquia", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdJerarquia")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreJerarquia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("_Id");

                    b.HasIndex("nombreJerarquia")
                        .IsUnique();

                    b.ToTable("Jerarquias");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Pais", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPais")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombrePais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("_Id");

                    b.HasIndex("nombrePais")
                        .IsUnique();

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Pais_Departamento", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDepartamentoPais")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("departamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("paisId")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("departamentoId");

                    b.HasIndex("paisId");

                    b.ToTable("Pais_Departamentos");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Sector", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSector")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreSector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("_Id");

                    b.HasIndex("nombreSector")
                        .IsUnique();

                    b.ToTable("Sectores");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Sucursal", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSucursal")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ciudadId")
                        .HasColumnType("int");

                    b.Property<string>("nombreSucursal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("_Id");

                    b.HasIndex("ciudadId");

                    b.HasIndex("nombreSucursal")
                        .IsUnique();

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Telefono", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTelefono")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("numeroTel")
                        .HasColumnType("bigint");

                    b.HasKey("_Id");

                    b.HasIndex("numeroTel")
                        .IsUnique();

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Telefono_Usuario", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTelefonoU")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TelefonoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("idTipoContacto")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("TelefonoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TelefonoUsuarios");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.TipoVivienda", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipoViVienda")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("_Id");

                    b.HasIndex("descripcion")
                        .IsUnique();

                    b.ToTable("TipoViviendas");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.TipoVivienda_Barrio", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipoViviendaB")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ciudadBId")
                        .HasColumnType("int");

                    b.Property<int?>("tipoViViendaId")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("ciudadBId");

                    b.HasIndex("tipoViViendaId");

                    b.ToTable("TipoVivienda_Barrios");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Usuario", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("_Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Zona", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdZona")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreZona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("_Id");

                    b.HasIndex("nombreZona")
                        .IsUnique();

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Zona_Localidad", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdZonaSector")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("sectorId")
                        .HasColumnType("int");

                    b.Property<int?>("zonaId")
                        .HasColumnType("int");

                    b.HasKey("_Id");

                    b.HasIndex("sectorId");

                    b.HasIndex("zonaId");

                    b.ToTable("Zona_Localidades");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Barrio_ZonaLocalidad", b =>
                {
                    b.HasOne("FuncEnCasa.App.Dominio.Zona_Localidad", "zonaL")
                        .WithMany("barrioZonaSector")
                        .HasForeignKey("ZonaLId");

                    b.HasOne("FuncEnCasa.App.Dominio.Barrio", "barrio")
                        .WithMany("barrioZonaSector")
                        .HasForeignKey("barrioId");

                    b.Navigation("barrio");

                    b.Navigation("zonaL");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Ciudad_BarrioZonaLocalidad", b =>
                {
                    b.HasOne("FuncEnCasa.App.Dominio.Barrio_ZonaLocalidad", "barrioZL")
                        .WithMany("ciudadBarrioZonaLocalidad")
                        .HasForeignKey("BarrioZLId");

                    b.HasOne("FuncEnCasa.App.Dominio.Ciudad", "ciudad")
                        .WithMany("ciudadBarrioZonaLocalidad")
                        .HasForeignKey("ciudadId");

                    b.Navigation("barrioZL");

                    b.Navigation("ciudad");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Ciudad_Departamento", b =>
                {
                    b.HasOne("FuncEnCasa.App.Dominio.Ciudad", "ciudad")
                        .WithMany("ciudadDepartamento")
                        .HasForeignKey("ciudadId");

                    b.HasOne("FuncEnCasa.App.Dominio.Departamento", "departamento")
                        .WithMany("ciudadDepartamento")
                        .HasForeignKey("departamentoId");

                    b.Navigation("ciudad");

                    b.Navigation("departamento");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Correo_Usuario", b =>
                {
                    b.HasOne("FuncEnCasa.App.Dominio.Correo", "correo")
                        .WithMany("correoUsuario")
                        .HasForeignKey("CorreoId");

                    b.HasOne("FuncEnCasa.App.Dominio.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("correo");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Direccion", b =>
                {
                    b.HasOne("FuncEnCasa.App.Dominio.TipoVivienda_Barrio", "tipoViviendaB")
                        .WithMany("direccion")
                        .HasForeignKey("tipoViviendaBId");

                    b.Navigation("tipoViviendaB");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Funcionario", b =>
                {
                    b.HasOne("FuncEnCasa.App.Dominio.Ciudad", "ciudad")
                        .WithMany("funcionario")
                        .HasForeignKey("ciudadId");

                    b.HasOne("FuncEnCasa.App.Dominio.Correo", "correo")
                        .WithMany("funcionario")
                        .HasForeignKey("correoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuncEnCasa.App.Dominio.Direccion", "direccion")
                        .WithMany("funcionario")
                        .HasForeignKey("direccionId");

                    b.HasOne("FuncEnCasa.App.Dominio.Sucursal", "sucursal")
                        .WithMany("funcionario")
                        .HasForeignKey("sucursalId");

                    b.HasOne("FuncEnCasa.App.Dominio.Telefono", "telefono")
                        .WithMany("funcionario")
                        .HasForeignKey("telefonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuncEnCasa.App.Dominio.Usuario", "usuario")
                        .WithMany("funcionario")
                        .HasForeignKey("usuarioId");

                    b.Navigation("ciudad");

                    b.Navigation("correo");

                    b.Navigation("direccion");

                    b.Navigation("sucursal");

                    b.Navigation("telefono");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Pais_Departamento", b =>
                {
                    b.HasOne("FuncEnCasa.App.Dominio.Departamento", "departamento")
                        .WithMany("paisDepartamento")
                        .HasForeignKey("departamentoId");

                    b.HasOne("FuncEnCasa.App.Dominio.Pais", "pais")
                        .WithMany("paisDepartamentos")
                        .HasForeignKey("paisId");

                    b.Navigation("departamento");

                    b.Navigation("pais");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Sucursal", b =>
                {
                    b.HasOne("FuncEnCasa.App.Dominio.Ciudad", "ciudad")
                        .WithMany("sucursal")
                        .HasForeignKey("ciudadId");

                    b.Navigation("ciudad");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Telefono_Usuario", b =>
                {
                    b.HasOne("FuncEnCasa.App.Dominio.Telefono", "telefono")
                        .WithMany("usuario")
                        .HasForeignKey("TelefonoId");

                    b.HasOne("FuncEnCasa.App.Dominio.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("telefono");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.TipoVivienda_Barrio", b =>
                {
                    b.HasOne("FuncEnCasa.App.Dominio.Ciudad_BarrioZonaLocalidad", "ciudadB")
                        .WithMany("TipoViviendaBarrio")
                        .HasForeignKey("ciudadBId");

                    b.HasOne("FuncEnCasa.App.Dominio.TipoVivienda", "tipoVivienda")
                        .WithMany("tipoViviendaBarrio")
                        .HasForeignKey("tipoViViendaId");

                    b.Navigation("ciudadB");

                    b.Navigation("tipoVivienda");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Zona_Localidad", b =>
                {
                    b.HasOne("FuncEnCasa.App.Dominio.Sector", "sector")
                        .WithMany("zonaLocalidad")
                        .HasForeignKey("sectorId");

                    b.HasOne("FuncEnCasa.App.Dominio.Zona", "zona")
                        .WithMany("zonaLocalidad")
                        .HasForeignKey("zonaId");

                    b.Navigation("sector");

                    b.Navigation("zona");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Barrio", b =>
                {
                    b.Navigation("barrioZonaSector");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Barrio_ZonaLocalidad", b =>
                {
                    b.Navigation("ciudadBarrioZonaLocalidad");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Ciudad", b =>
                {
                    b.Navigation("ciudadBarrioZonaLocalidad");

                    b.Navigation("ciudadDepartamento");

                    b.Navigation("funcionario");

                    b.Navigation("sucursal");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Ciudad_BarrioZonaLocalidad", b =>
                {
                    b.Navigation("TipoViviendaBarrio");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Correo", b =>
                {
                    b.Navigation("correoUsuario");

                    b.Navigation("funcionario");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Departamento", b =>
                {
                    b.Navigation("ciudadDepartamento");

                    b.Navigation("paisDepartamento");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Direccion", b =>
                {
                    b.Navigation("funcionario");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Pais", b =>
                {
                    b.Navigation("paisDepartamentos");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Sector", b =>
                {
                    b.Navigation("zonaLocalidad");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Sucursal", b =>
                {
                    b.Navigation("funcionario");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Telefono", b =>
                {
                    b.Navigation("funcionario");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.TipoVivienda", b =>
                {
                    b.Navigation("tipoViviendaBarrio");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.TipoVivienda_Barrio", b =>
                {
                    b.Navigation("direccion");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Usuario", b =>
                {
                    b.Navigation("funcionario");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Zona", b =>
                {
                    b.Navigation("zonaLocalidad");
                });

            modelBuilder.Entity("FuncEnCasa.App.Dominio.Zona_Localidad", b =>
                {
                    b.Navigation("barrioZonaSector");
                });
#pragma warning restore 612, 618
        }
    }
}
